import type {
  Metabolite,
  SalesData,
  InventoryData,
  DashboardStats,
  ChartDataPoint,
  SearchItem,
  FeatureTable,
  DatasetContribution,
} from "./types";

export const NAV_ITEMS = [
  { label: "Domains Hub", href: "/dashboard" },
  { label: "Metabolites & Spectra", href: "/medications" },
  { label: "Data Repositories", href: "/reports" },
  { label: "Analytical Bio-Map", href: "/analytics" },
  { label: "Metadata & DOIs", href: "/settings" },
] as const;

export const DASHBOARD_STATS: DashboardStats = {
  totalTerms: 48920,       // Annotated Metabolites across domains
  monthlyLookups: 184200,   // Monthly Spectral Matching Queries
  libraryArticles: 3450,    // Curated Datasets with Persistent DOIs
  drugEntries: 14200,      // Reference Spectral Libraries (LC-MS/MS, GC-MS, NMR)
  termsChange: 14.8,
  lookupsChange: 12.3,
  articlesChange: 18.5,
  drugsChange: 9.1,
};

export const SALES_DATA: SalesData[] = [
  { date: "Jan", revenue: 12400, orders: 8420, profit: 3520 },
  { date: "Feb", revenue: 15800, orders: 9680, profit: 4280 },
  { date: "Mar", revenue: 14200, orders: 9150, profit: 3890 },
  { date: "Apr", revenue: 18900, orders: 11890, profit: 5120 },
  { date: "May", revenue: 17100, orders: 10720, profit: 4640 },
  { date: "Jun", revenue: 22400, orders: 14150, profit: 6270 },
  { date: "Jul", revenue: 20800, orders: 13180, profit: 5790 },
  { date: "Aug", revenue: 25600, orders: 15310, profit: 7110 },
  { date: "Sep", revenue: 23100, orders: 14080, profit: 6380 },
  { date: "Oct", revenue: 28400, orders: 17480, profit: 8180 },
  { date: "Nov", revenue: 26200, orders: 16200, profit: 7470 },
  { date: "Dec", revenue: 31500, orders: 19720, profit: 9280 },
];

export const INVENTORY_DATA: InventoryData[] = [
  { category: "Plant Metabolomics", complete: 185, partial: 32, missing: 8 },
  { category: "Agricultural Metabolomics", complete: 142, partial: 28, missing: 6 },
  { category: "Environmental Metabolomics", complete: 98, partial: 19, missing: 4 },
  { category: "Livestock Metabolomics", complete: 76, partial: 14, missing: 3 },
  { category: "Human Metabolomics", complete: 45, partial: 12, missing: 5 },
];

export const CATEGORY_DISTRIBUTION: ChartDataPoint[] = [
  { name: "Plant Metabolomics", value: 34, fill: "#f43f5e" },
  { name: "Agricultural Metabolomics", value: 26, fill: "#fb7185" },
  { name: "Environmental Metabolomics", value: 18, fill: "#fda4af" },
  { name: "Livestock Metabolomics", value: 14, fill: "#fecdd3" },
  { name: "Human Metabolomics", value: 8, fill: "#ffe4e6" },
];

export const TOP_MEDICATIONS: ChartDataPoint[] = [
  { name: "Artemisinin", value: 3420 },
  { name: "Vernolepin", value: 2890 },
  { name: "Quercetin 3-O-glucoside", value: 2450 },
  { name: "Sorghum Stress Metabolite S-14", value: 2120 },
  { name: "Cattle Rumen Lipid L-08", value: 1890 },
  { name: "Aframomum Flavonoid A-02", value: 1650 },
  { name: "Rhizosphere Exudate R-11", value: 1420 },
  { name: "Aquatic Exometabolome E-05", value: 1280 },
];

export const WEEKLY_TRAFFIC: ChartDataPoint[] = [
  { name: "Mon", value: 3420 },
  { name: "Tue", value: 3180 },
  { name: "Wed", value: 4510 },
  { name: "Thu", value: 4160 },
  { name: "Fri", value: 5290 },
  { name: "Sat", value: 6120 },
  { name: "Sun", value: 2840 },
];

export const MONTHLY_PRESCRIPTIONS: ChartDataPoint[] = [
  { name: "Week 1", value: 2320 },
  { name: "Week 2", value: 2880 },
  { name: "Week 3", value: 3150 },
  { name: "Week 4", value: 2790 },
];

export const PERFORMANCE_DATA = [
  { name: "Q1", target: 40000, actual: 42500 },
  { name: "Q2", target: 45000, actual: 48200 },
  { name: "Q3", target: 50000, actual: 53900 },
  { name: "Q4", target: 55000, actual: 59100 },
];

export const ARTICLES_BY_SPECIALTY: ChartDataPoint[] = [
  { name: "Plant Metabolomics", value: 1240, fill: "#22d3ee" },
  { name: "Agricultural Metabolomics", value: 980, fill: "#06b6d4" },
  { name: "Environmental Metabolomics", value: 650, fill: "#0891b2" },
  { name: "Livestock Metabolomics", value: 420, fill: "#0e7490" },
  { name: "Human Metabolomics", value: 280, fill: "#155e75" },
];

export const REVIEW_RELIABILITY = [
  { name: "Curator Board A (Plants)", score: 98, fill: "#22c55e" },
  { name: "Curator Board B (Crops)", score: 94, fill: "#22c55e" },
  { name: "Curator Board C (Environment)", score: 91, fill: "#22c55e" },
  { name: "Curator Board D (Livestock)", score: 89, fill: "#22c55e" },
  { name: "Curator Board E (Human)", score: 86, fill: "#eab308" },
];

export const SAMPLE_METABOLITES: Metabolite[] = [
  {
    id: "m-01",
    name: "Artemisinin",
    category: "Phytochemical / Sesquiterpene Lactone",
    formula: "C15H22O5",
    exactMass: 282.1467,
    mz: 283.1540,
    retentionTime: 7.42,
    platform: "LC-MS/MS",
    domain: "Plant Metabolomics",
    structureSmiles: "CC1CCC2C(C1)C(=O)OC3C2(C4C(O3)C(C(=O)O4)C)C",
    confidenceScore: 98.5,
    metadata: {
      speciesName: "Artemisia annua L.",
      tissueType: "Leaf Trichomes",
      geographicOrigin: "East Africa (Madagascar / Kenya)",
      environmentalConditions: "Sub-humid tropical highlands",
      sampleCollectionMethod: "Fresh leaf flash-freezing in liquid N2",
      sampleStorageConditions: "-80°C ultra-low freezer storage",
    },
    databaseIds: {
      metaboLights: "MTBLS4810",
      gnps: "CCMSLIB000054321",
      pubchem: "68827",
      doi: "10.5281/zenodo.AMDB-2026-001",
    },
    description: "Potent antimalarial sesquiterpene lactone extracted from medicinal plant biodiversity.",
    dosage: "m/z 283.1540 [M+H]+",
    price: 98.5,
    stock: 1420,
    expiryDate: "Level 1 Ident",
    manufacturer: "MetaboLights & Literature",
  },
  {
    id: "m-02",
    name: "Vernolepin",
    category: "Medicinal Plant Bioactive",
    formula: "C15H16O5",
    exactMass: 276.0998,
    mz: 277.1071,
    retentionTime: 5.18,
    platform: "LC-MS/MS",
    domain: "Plant Metabolomics",
    structureSmiles: "C=C1C(=O)OC2C1CC3C(C2=O)C(=C)C(=O)O3",
    confidenceScore: 94.0,
    metadata: {
      speciesName: "Vernonia amygdalina (Bitter Leaf)",
      tissueType: "Foliar extract",
      geographicOrigin: "West Africa (Nigeria / Ghana)",
      environmentalConditions: "Guinean savanna border",
      sampleCollectionMethod: "Methanol-water ultrasonic extraction",
      sampleStorageConditions: "-20°C desiccation",
    },
    databaseIds: {
      metaboLights: "MTBLS3912",
      pubchem: "160864",
      doi: "10.5281/zenodo.AMDB-2026-002",
    },
    description: "Bioactive sesquiterpene lactone with anti-inflammatory and cellular protective effects.",
    dosage: "m/z 277.1071 [M+H]+",
    price: 94.0,
    stock: 980,
    expiryDate: "Level 1 Ident",
    manufacturer: "African Herbal Flora DB",
  },
  {
    id: "m-03",
    name: "Sorghum Dhurrin Stress Signature",
    category: "Crop Stress Response / Cyanogenic Glucoside",
    formula: "C14H17NO7",
    exactMass: 311.1005,
    mz: 312.1078,
    retentionTime: 4.85,
    platform: "LC-MS/MS",
    domain: "Agricultural Metabolomics",
    structureSmiles: "N#CC(C1=CC=C(O)C=C1)OC2C(C(C(C(O2)CO)O)O)O",
    confidenceScore: 96.2,
    metadata: {
      speciesName: "Sorghum bicolor (L.) Moench",
      tissueType: "Drought-stressed seedling root",
      geographicOrigin: "Sahel Region (Burkina Faso / Niger)",
      environmentalConditions: "Severe drought stress (20% Field Capacity)",
      sampleCollectionMethod: "Root wash & freeze-drying",
      sampleStorageConditions: "-80°C under nitrogen gas",
    },
    databaseIds: {
      metaboLights: "MTBLS5102",
      gnps: "CCMSLIB000088910",
      pubchem: "119032",
      doi: "10.5281/zenodo.AMDB-2026-003",
    },
    description: "Key metabolic stress indicator regulating herbivore defense and osmotic tolerance in Sorghum crops.",
    dosage: "m/z 312.1078 [M+H]+",
    price: 96.2,
    stock: 1250,
    expiryDate: "Level 1 Ident",
    manufacturer: "ICRISAT & AMDB Crop Network",
  },
  {
    id: "m-04",
    name: "Rhizosphere Nitrogen-Fixing Signalling Metabolite",
    category: "Plant-Microbe Interaction Marker",
    formula: "C15H10O6",
    exactMass: 286.0477,
    mz: 285.0404,
    retentionTime: 8.12,
    platform: "LC-MS/MS",
    domain: "Agricultural Metabolomics",
    structureSmiles: "C1=CC(=CC=C1C2=CC(=O)C3=C(C=C(C=C3O2)O)O)O",
    confidenceScore: 92.4,
    metadata: {
      speciesName: "Vigna unguiculata (Cowpea) + Bradyrhizobium",
      tissueType: "Rhizosphere soil & root exudate",
      geographicOrigin: "West Africa (Nigeria / Benin)",
      environmentalConditions: "Nitrogen-deficient sandy loam soil",
      sampleCollectionMethod: "Rhizosphere soil centrifugation & SPE elution",
      sampleStorageConditions: "-80°C lyophilized",
    },
    databaseIds: {
      metaboLights: "MTBLS2840",
      doi: "10.5281/zenodo.AMDB-2026-004",
    },
    description: "Flavonoid nodulation gene inducer mediating plant-microbe symbiotic nitrogen fixation.",
    dosage: "m/z 285.0404 [M-H]-",
    price: 92.4,
    stock: 870,
    expiryDate: "Level 2 Ident",
    manufacturer: "Soil Metabolic Signatures Lab",
  },
  {
    id: "m-05",
    name: "Cattle Rumen Bioactive Conjugated Linoleic Acid",
    category: "Feed Metabolite & Health Indicator",
    formula: "C18H32O2",
    exactMass: 280.2402,
    mz: 281.2475,
    retentionTime: 14.30,
    platform: "GC-MS",
    domain: "Livestock Metabolomics",
    structureSmiles: "CCCCCCCC/C=C/C=C/CCCCCCCC(=O)O",
    confidenceScore: 97.0,
    metadata: {
      speciesName: "Bos indicus (Zebu Cattle)",
      tissueType: "Rumen fluid & plasma",
      geographicOrigin: "East African Rift Valley (Kenya / Ethiopia)",
      environmentalConditions: "Pasture forage fed during dry season",
      sampleCollectionMethod: "Esophageal tube rumen sampling & derivatization",
      sampleStorageConditions: "-80°C",
    },
    databaseIds: {
      metaboLights: "MTBLS6201",
      pubchem: "5280644",
      doi: "10.5281/zenodo.AMDB-2026-005",
    },
    description: "Biomarker of animal digestive health, pasture feed quality, and productivity in indigenous cattle.",
    dosage: "m/z 281.2475 [M+H]+",
    price: 97.0,
    stock: 1100,
    expiryDate: "Level 1 Ident",
    manufacturer: "ILRI Livestock Metabolomics",
  },
  {
    id: "m-06",
    name: "Sub-Saharan Soil Humic Microbial Exometabolite",
    category: "Soil Metabolome Chemistry",
    formula: "C20H18O8",
    exactMass: 386.1002,
    mz: 387.1075,
    retentionTime: 11.65,
    platform: "NMR Spectroscopy",
    domain: "Environmental Metabolomics",
    structureSmiles: "CC1=C(C(=O)C2=C(C1=O)C(=C(C=C2O)O)C(=O)O)C3=CC=CC=C3",
    confidenceScore: 91.8,
    metadata: {
      speciesName: "Microbial Environmental Consortium",
      tissueType: "Soil organic matter extract",
      geographicOrigin: "Congo Basin Rainforest Soil",
      environmentalConditions: "Intense seasonal rainfall & high organic humus",
      sampleCollectionMethod: "Core soil sampling 0-15cm depth & NMR extraction",
      sampleStorageConditions: "Dry cold room at +4°C",
    },
    databaseIds: {
      metaboLights: "MTBLS7104",
      doi: "10.5281/zenodo.AMDB-2026-006",
    },
    description: "Environmental soil metabolome signature characterizing carbon sequestration and microbial decay.",
    dosage: "NMR 1H Spectrum 3.8-7.2 ppm",
    price: 91.8,
    stock: 640,
    expiryDate: "Level 2 Ident",
    manufacturer: "African Environmental Met. Initiative",
  },
  {
    id: "m-07",
    name: "Aframomum Melegueta Gingerol Derivative",
    category: "Wild Plant Phytochemical",
    formula: "C17H26O4",
    exactMass: 294.1831,
    mz: 295.1904,
    retentionTime: 9.15,
    platform: "LC-MS/MS",
    domain: "Plant Metabolomics",
    structureSmiles: "CCCCCC(O)CC(=O)CCC1=CC(=C(C=C1)O)OC",
    confidenceScore: 95.8,
    metadata: {
      speciesName: "Aframomum melegueta (Grains of Paradise)",
      tissueType: "Seed extract",
      geographicOrigin: "West Africa (Ghana / Ivory Coast)",
      environmentalConditions: "Tropical rainforest understory",
      sampleCollectionMethod: "Supercritical CO2 extraction",
      sampleStorageConditions: "-20°C amber glass vial",
    },
    databaseIds: {
      metaboLights: "MTBLS1905",
      pubchem: "442793",
      doi: "10.5281/zenodo.AMDB-2026-007",
    },
    description: "Pungent bioactive ketone with thermogenic and antimicrobial properties.",
    dosage: "m/z 295.1904 [M+H]+",
    price: 95.8,
    stock: 1320,
    expiryDate: "Level 1 Ident",
    manufacturer: "AMDB Phytochemical Consortium",
  },
  {
    id: "m-08",
    name: "Nutritional Microbiome Metabolite Isobutyrate",
    category: "Microbiome-Host Health Marker",
    formula: "C4H8O2",
    exactMass: 88.0524,
    mz: 89.0597,
    retentionTime: 2.10,
    platform: "GC-MS",
    domain: "Human Metabolomics",
    structureSmiles: "CC(C)C(=O)O",
    confidenceScore: 99.1,
    metadata: {
      speciesName: "Homo sapiens (Cohort Cohort-AF)",
      tissueType: "Stool & serum short-chain fatty acid",
      geographicOrigin: "Urban & Rural Cohorts (South Africa / Uganda)",
      environmentalConditions: "Traditional vs Urbanized dietary profiles",
      sampleCollectionMethod: "Immediate acidification & ether extraction",
      sampleStorageConditions: "-80°C biobank storage",
    },
    databaseIds: {
      metaboLights: "MTBLS8802",
      pubchem: "6590",
      doi: "10.5281/zenodo.AMDB-2026-008",
    },
    description: "Short-chain fatty acid metabolic indicator of gut microbial fermentative health and dietary fiber intake.",
    dosage: "m/z 89.0597 [M+H]+",
    price: 99.1,
    stock: 1540,
    expiryDate: "Level 1 Ident",
    manufacturer: "African Human Biobank Initiative",
  },
];

export const FEATURE_TABLES_DATA: FeatureTable[] = [
  {
    id: "ft-101",
    title: "Medicinal Flora Phytochemical Profiling of East Africa",
    domain: "Plant Metabolomics",
    sampleCount: 128,
    detectedFeatures: 4210,
    alignmentMethod: "XCMS / MZmine 3 Peak Alignment",
    species: "Artemisia annua, Catharanthus roseus, Moringa oleifera",
    geographicRegion: "Madagascar, Kenya, Tanzania",
    publicRepoSource: "MetaboLights",
    doi: "10.5281/zenodo.AMDB-2026-FT01",
    contributor: "Dr. A. Oladipo & East African Herbarium Team",
    institution: "Nairobi Botanical & Metabolomics Institute",
    createdDate: "2026-02-14",
  },
  {
    id: "ft-102",
    title: "Sahel Crop Drought Resilience Metabolomic Callset",
    domain: "Agricultural Metabolomics",
    sampleCount: 256,
    detectedFeatures: 6890,
    alignmentMethod: "MS-DIAL 4.9 Alignment Engine",
    species: "Sorghum bicolor, Vigna unguiculata (Cowpea)",
    geographicRegion: "Burkina Faso, Mali, Niger",
    publicRepoSource: "Community Submission",
    doi: "10.5281/zenodo.AMDB-2026-FT02",
    contributor: "Prof. K. Mensah",
    institution: "West African Crop Research Consortium",
    createdDate: "2026-01-20",
  },
  {
    id: "ft-103",
    title: "Indigenous Pasture Feed Rumen Metabolomes",
    domain: "Livestock Metabolomics",
    sampleCount: 94,
    detectedFeatures: 3150,
    alignmentMethod: "OpenMS FeatureFinderMetabo",
    species: "Bos indicus (Zebu), Capra hircus (West African Dwarf Goat)",
    geographicRegion: "Rift Valley & Sahel Pastoral Zones",
    publicRepoSource: "GNPS",
    doi: "10.5281/zenodo.AMDB-2026-FT03",
    contributor: "Dr. S. Ndiaye",
    institution: "International Livestock Research Institute",
    createdDate: "2025-11-30",
  },
  {
    id: "ft-104",
    title: "Lake Victoria & Congo Basin Aquatic Environmental Chemistry",
    domain: "Environmental Metabolomics",
    sampleCount: 180,
    detectedFeatures: 5420,
    alignmentMethod: "MetaboAnalyst 5.0 Auto-Alignment",
    species: "Aquatic microbial exometabolome",
    geographicRegion: "Lake Victoria Basin & Congo River",
    publicRepoSource: "Metabolomics Workbench",
    doi: "10.5281/zenodo.AMDB-2026-FT04",
    contributor: "Dr. C. Mutua",
    institution: "African Aquatic Ecosystem Network",
    createdDate: "2025-10-18",
  },
];

export const DATASET_CONTRIBUTIONS: DatasetContribution[] = [
  {
    id: "ds-01",
    title: "Pan-African Phytochemical Spectral Library (2026 Release)",
    doi: "10.5281/zenodo.AMDB-2026-DS01",
    authors: ["Oladipo A.", "Mensah K.", "Abebe T.", "Sithole M."],
    institution: "African Metabolome Consortium",
    domain: "Plant Metabolomics",
    publicSource: "MetaboLights & Literature",
    featureTableCount: 14,
    sampleCount: 840,
    publicationDate: "2026-01-15",
    citationFormat: "Oladipo et al. (2026). Pan-African Phytochemical Spectral Library. African Metabolome DB, DOI: 10.5281/zenodo.AMDB-2026-DS01",
    metadataDescription: "Curated spectral reference LC-MS/MS profiles for 450 medicinal plant species across 12 African bioclimatic zones.",
  },
  {
    id: "ds-02",
    title: "Crop-Soil-Microbe Symbiosis Metabolomic Dataset",
    doi: "10.5281/zenodo.AMDB-2026-DS02",
    authors: ["Mensah K.", "Ndiaye S.", "Biobaku O."],
    institution: "CGIAR / AMDB Crop Node",
    domain: "Agricultural Metabolomics",
    publicSource: "Community Contributions",
    featureTableCount: 8,
    sampleCount: 512,
    publicationDate: "2025-12-10",
    citationFormat: "Mensah et al. (2025). Crop-Soil-Microbe Symbiosis Dataset. AMDB Open Data, DOI: 10.5281/zenodo.AMDB-2026-DS02",
    metadataDescription: "High-resolution LC-MS feature tables evaluating drought stress and nitrogen fixation in West African cereal legumes.",
  },
];

export const CHART_COLORS = {
  primary: "#f43f5e",
  secondary: "#fb7185",
  tertiary: "#fda4af",
  success: "#22c55e",
  warning: "#eab308",
  danger: "#ef4444",
  info: "#06b6d4",
  muted: "#94a3b8",
};

export const SEARCH_INDEX: SearchItem[] = [
  // ---- Plant Metabolites ----
  { id: "m-01", label: "Artemisinin", type: "Metabolite", category: "Plant Metabolomics", domain: "Plant Metabolomics", description: "Potent antimalarial sesquiterpene lactone from Artemisia annua.", mz: 283.1540, platform: "LC-MS/MS", species: "Artemisia annua", doi: "10.5281/zenodo.AMDB-2026-001", media: { format: "formula", value: "C15H22O5" } },
  { id: "m-02", label: "Vernolepin", type: "Metabolite", category: "Plant Metabolomics", domain: "Plant Metabolomics", description: "Anti-inflammatory phytochemical from Vernonia amygdalina (Bitter Leaf).", mz: 277.1071, platform: "LC-MS/MS", species: "Vernonia amygdalina", doi: "10.5281/zenodo.AMDB-2026-002", media: { format: "formula", value: "C15H16O5" } },
  { id: "m-07", label: "Aframomum Gingerol Derivative", type: "Metabolite", category: "Plant Metabolomics", domain: "Plant Metabolomics", description: "Pungent bioactive ketone from Grains of Paradise seeds.", mz: 295.1904, platform: "LC-MS/MS", species: "Aframomum melegueta", doi: "10.5281/zenodo.AMDB-2026-007", media: { format: "formula", value: "C17H26O4" } },
  { id: "p-01", label: "Catharanthus roseus Alkaloid Profile", type: "Spectrum", category: "Plant Metabolomics", domain: "Plant Metabolomics", description: "LC-MS/MS spectral fragmentation library for Madagascar periwinkle vinblastine precursors.", mz: 811.412, platform: "LC-MS/MS", species: "Catharanthus roseus", doi: "10.5281/zenodo.AMDB-2026-P01" },
  { id: "p-02", label: "Hashubanonine", type: "Metabolite", category: "Plant Metabolomics", domain: "Plant Metabolomics", description: "Morphinan-type alkaloid identified from Ethiopian Stephania abyssinica.", mz: 374.196, platform: "LC-MS/MS", species: "Stephania abyssinica", media: { format: "formula", value: "C21H27NO5" } },

  // ---- Agricultural Metabolites ----
  { id: "m-03", label: "Sorghum Dhurrin Stress Signature", type: "Metabolite", category: "Agricultural Metabolomics", domain: "Agricultural Metabolomics", description: "Cyanogenic glucoside regulating drought tolerance in Sorghum crops.", mz: 312.1078, platform: "LC-MS/MS", species: "Sorghum bicolor", doi: "10.5281/zenodo.AMDB-2026-003", media: { format: "formula", value: "C14H17NO7" } },
  { id: "m-04", label: "Rhizosphere Nodulation Flavonoid", type: "Metabolite", category: "Agricultural Metabolomics", domain: "Agricultural Metabolomics", description: "Plant-microbe interaction signaling marker inducing nitrogen fixation.", mz: 285.0404, platform: "LC-MS/MS", species: "Vigna unguiculata", doi: "10.5281/zenodo.AMDB-2026-004", media: { format: "formula", value: "C15H10O6" } },
  { id: "a-01", label: "Maize Root Exudate Phenolic Signature", type: "Spectrum", category: "Agricultural Metabolomics", domain: "Agricultural Metabolomics", description: "Root exudate spectral profile under soil phosphorus deficiency.", mz: 195.065, platform: "LC-MS/MS", species: "Zea mays" },

  // ---- Livestock Metabolites ----
  { id: "m-05", label: "Cattle Rumen Bioactive CLA", type: "Metabolite", category: "Livestock Metabolomics", domain: "Livestock Metabolomics", description: "Conjugated linoleic acid indicator of pasture feed quality and digestive health in Zebu cattle.", mz: 281.2475, platform: "GC-MS", species: "Bos indicus", doi: "10.5281/zenodo.AMDB-2026-005", media: { format: "formula", value: "C18H32O2" } },
  { id: "l-01", label: "Goat Plasma Growth Biomarker Lipid", type: "Metabolite", category: "Livestock Metabolomics", domain: "Livestock Metabolomics", description: "Plasma phospholipid biomarker associated with daily weight gain in West African Dwarf goats.", mz: 520.341, platform: "LC-MS/MS", species: "Capra hircus" },

  // ---- Environmental Metabolites ----
  { id: "m-06", label: "Sub-Saharan Soil Humic Exometabolite", type: "Metabolite", category: "Environmental Metabolomics", domain: "Environmental Metabolomics", description: "Soil organic matter signature characterizing rainforest microbial decay.", platform: "NMR Spectroscopy", species: "Microbial Consortium", doi: "10.5281/zenodo.AMDB-2026-006", media: { format: "formula", value: "C20H18O8" } },
  { id: "e-01", label: "Lake Victoria Cyanobacterial Exometabolome", type: "Spectrum", category: "Environmental Metabolomics", domain: "Environmental Metabolomics", description: "Freshwater aquatic metabolome features and microcystin precursor spectra.", mz: 995.556, platform: "LC-MS/MS", species: "Aquatic Cyanobacteria" },

  // ---- Human Metabolomics ----
  { id: "m-08", label: "Nutritional Isobutyrate SCFA", type: "Metabolite", category: "Human Metabolomics", domain: "Human Metabolomics", description: "Short-chain fatty acid biomarker of gut microbiome fermentative health in African cohorts.", mz: 89.0597, platform: "GC-MS", species: "Homo sapiens", doi: "10.5281/zenodo.AMDB-2026-008", media: { format: "formula", value: "C4H8O2" } },

  // ---- Datasets & Repositories ----
  { id: "ds-01", label: "Pan-African Phytochemical Spectral Library", type: "Dataset", category: "Public Repository Dataset", domain: "Plant Metabolomics", description: "Reference spectral LC-MS/MS dataset covering 450 medicinal plant species with DOIs.", doi: "10.5281/zenodo.AMDB-2026-DS01" },
  { id: "ds-02", label: "Crop-Soil-Microbe Symbiosis Feature Table", type: "Dataset", category: "Community Contribution", domain: "Agricultural Metabolomics", description: "High-resolution feature tables assessing drought stress response in African crops.", doi: "10.5281/zenodo.AMDB-2026-DS02" },
];